### ISSUE TITLE
Stream Closed error.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-plugin-handler-server#45]
```
2023-10-09 19:47:30.191 INFO  v.s.InstallDataHandler - install-meta (for install-data) script completed successfully for VDI dataset ID ixX6542aKSMAAQ
2023-10-09 19:47:30.191 INFO  v.s.InstallDataHandler - executing check-compatibility script for VDI dataset ID ixX6542aKSMAAQ
2023-10-09 19:47:30.199 ERROR ExceptionMiddleware - Uncaught exception
 java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:164) ~[?:?]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125) ~[?:?]
	at java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:251) ~[?:?]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:245) ~[?:?]
	at java.io.FilterOutputStream.close(FilterOutputStream.java:182) ~[?:?]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:443) ~[?:?]
	at sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:241) ~[?:?]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:226) ~[?:?]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:267) ~[?:?]
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:56) ~[service.jar:?]
	at vdi.service.InstallDataHandler$runCheckDependencies$2$1.invokeSuspend(InstallDataHandler.kt:127) ~[service.jar:?]
	at vdi.service.InstallDataHandler$runCheckDependencies$2$1.invoke(InstallDataHandler.kt) ~[service.jar:?]
	at vdi.service.InstallDataHandler$runCheckDependencies$2$1.invoke(InstallDataHandler.kt) ~[service.jar:?]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78) ~[service.jar:?]
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264) ~[service.jar:?]
	at vdi.service.InstallDataHandler$runCheckDependencies$2.invokeSuspend(InstallDataHandler.kt:125) ~[service.jar:?]
	at vdi.service.InstallDataHandler$runCheckDependencies$2.invoke(InstallDataHandler.kt) ~[service.jar:?]
	at vdi.service.InstallDataHandler$runCheckDependencies$2.invoke(InstallDataHandler.kt) ~[service.jar:?]
	at vdi.components.script.ScriptExecutorImpl$executeScript$2.invokeSuspend(ScriptExecutorImpl.kt:21) ~[service.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[service.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[service.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) ~[service.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100) ~[service.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[service.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[service.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[service.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[service.jar:?]
```

**Comment by Foxcapades** [comment]
Fixed
